[#2312] kernel_test and reserve_mem test script update
git-svn-id: svn://localhost/svn/uclinux-dist/trunk@5626 3e2a5524-39e8-4cb9-84a9-c49da69cba3a

diff --git a/testsuites/kernel_test b/testsuites/kernel_test
--- a/testsuites/kernel_test
+++ b/testsuites/kernel_test
@@ -309,9 +309,9 @@ do
   fi
   
   ./build_${AUTO_TESTCASE[$i]}_kernel.exp $BOARD_TYPE  >/dev/null  2>&1
-  if [ ! -f $UCLINUX_DIST_PATH/images/linux ] && [ ${AUTO_TESTCASE[$i]} != "gpio" ] && [ ${AUTO_TESTCASE[$i]} != "jffs2" ]
+  if ([ ! -f $UCLINUX_DIST_PATH/images/linux ] && [ ${AUTO_TESTCASE[$i]} != "gpio" ] && [ ${AUTO_TESTCASE[$i]} != "jffs2" ]) || ([ ${AUTO_TESTCASE[$i]} == "xip" ] && [ ! -f $UCLINUX_DIST_PATH/images/linux.romfs ])
   then
-        echo "$0:   Error, failed."
+	echo "$0:   Error, failed."
 	tail -50 ./build_${AUTO_TESTCASE[$i]}_kernel_log
   else
  	sleep 30
