+ This adds the possibility of turning the HISTORY file maintenance on and off in the script.

diff --git a/do-tag b/do-tag
--- a/do-tag
+++ b/do-tag
@@ -68,6 +68,8 @@ update_files() {
 	VERSION_RC=$5
 }
 
+OPT_MAINTAIN_HISTORY_FILE=1
+
 [ "$1" == "--help" ] && { help; exit; }
 
 [ "$1" ] && ARG_VERSION=$1 || usage "Version specification missing!"
@@ -93,18 +95,21 @@ update_files "$ARG_VERSION" "$VERSION_MAJOR" "$VERSION_MINOR" "$VERSION_PATCH" "
 		UPDATED_FILES=("${UPDATED_FILES[@]}" "$i")
 	done
 	
-	VERSIONS_FILE="HISTORY"
-	TEMP_FILE="HISTORY.add"
-	
 	if [ $VERSION_RC -eq 0 ]; then
-		[ "$EDITOR" ] || EDITOR=$(git config "core.editor")
-		[ "$EDITOR" ] || fail "\$EDITOR is not set. Please set the EDITOR environment variable to input the release notes."
+		RELEASE_NOTE="+ Release $ARG_VERSION"
 		
-		if ! [ -e "$TEMP_FILE" ]; then
-			NEWEST_RELEASE=$(git tag | grep -E "release/.*" | while IFS= read i; do echo "$(git rev-list "$i..HEAD" | wc -l | grep -oE "[0-9]+") $i"; done | sort -n | head -n 1 | cut -d " " -f 2-)
+		if [ "$OPT_MAINTAIN_HISTORY_FILE" ]; then
+			VERSIONS_FILE="HISTORY"
+			TEMP_FILE="HISTORY.add"
 			
-			cat << EOF >> "$TEMP_FILE"
-+ Release $ARG_VERSION
+			[ "$EDITOR" ] || EDITOR=$(git config "core.editor")
+			[ "$EDITOR" ] || fail "\$EDITOR is not set. Please set the EDITOR environment variable to input the release notes."
+			
+			if ! [ -e "$TEMP_FILE" ]; then
+				NEWEST_RELEASE=$(git tag | grep -E "release/.*" | while IFS= read i; do echo "$(git rev-list "$i..HEAD" | wc -l | grep -oE "[0-9]+") $i"; done | sort -n | head -n 1 | cut -d " " -f 2-)
+				
+				cat << EOF >> "$TEMP_FILE"
+$RELEASE_NOTE
 
 
 # Please enter your release note above under the line with the version
@@ -113,32 +118,33 @@ update_files "$ARG_VERSION" "$VERSION_MAJOR" "$VERSION_MINOR" "$VERSION_PATCH" "
 
 # To abort the commit, empty this file before exiting your editor.
 EOF
-			if [ "$NEWEST_RELEASE" ]; then
-				cat << EOF >> "$TEMP_FILE"
+				if [ "$NEWEST_RELEASE" ]; then
+					cat << EOF >> "$TEMP_FILE"
 
 # Changes since the last release, $NEWEST_RELEASE:
 #
 EOF
-				git diff --stat | sed -r "s/^/#/" >> "$TEMP_FILE"
+					git diff --stat | sed -r "s/^/#/" >> "$TEMP_FILE"
+				fi
 			fi
+			
+			$EDITOR "$TEMP_FILE"
+			
+			RELEASE_NOTE=$(grep -vE "^ *#" < "$TEMP_FILE")
+			if ! [ "$(echo "$RELEASE_NOTE" | sed -r "s/\t/ /g" | grep -vE "^ *(#.*)?$")" ]; then
+				rm -f "$TEMP_FILE"
+				fail "Commit aborted due to empty commit message."
+			fi
+			
+			echo "$RELEASE_NOTE" > "$VERSIONS_FILE"
+			if git show "HEAD:$VERSIONS_FILE" > /dev/null 2>&1; then
+				echo -e '\n' >> $VERSIONS_FILE
+				git show "HEAD:$VERSIONS_FILE" >> $VERSIONS_FILE
+			fi
+			
+			git add "$VERSIONS_FILE" || exit $?
+			UPDATED_FILES=("${UPDATED_FILES[@]}" "$VERSIONS_FILE")
 		fi
-		
-		$EDITOR "$TEMP_FILE"
-		
-		RELEASE_NOTE=$(grep -vE "^ *#" < "$TEMP_FILE")
-	 	if ! [ "$(echo "$RELEASE_NOTE" | sed -r "s/\t/ /g" | grep -vE "^ *(#.*)?$")" ]; then
-	 		rm -f "$TEMP_FILE"
-	 		fail "Commit aborted due to empty commit message."
-	 	fi
-	 	
-		echo "$RELEASE_NOTE" > "$VERSIONS_FILE"
-	 	if git show "HEAD:$VERSIONS_FILE" > /dev/null 2>&1; then
-	 		echo -e '\n' >> $VERSIONS_FILE
-	 		git show "HEAD:$VERSIONS_FILE" >> $VERSIONS_FILE
-	 	fi
-		
-		git add "$VERSIONS_FILE" || exit $?
-		UPDATED_FILES=("${UPDATED_FILES[@]}" "$VERSIONS_FILE")
 	else
 		RELEASE_NOTE="+ Beta version $ARG_VERSION"
 	fi
