Fix mmap emulation bug [#2616], this patch is from latest alsa development tree
git-svn-id: svn://localhost/svn/uclinux-dist/trunk@5491 3e2a5524-39e8-4cb9-84a9-c49da69cba3a

diff --git a/lib/alsa-lib/alsa-lib-1.0.12/configure b/lib/alsa-lib/alsa-lib-1.0.12/configure
--- a/lib/alsa-lib/alsa-lib-1.0.12/configure
+++ b/lib/alsa-lib/alsa-lib-1.0.12/configure
@@ -464,7 +464,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar INSTALL_M4_TRUE INSTALL_M4_FALSE CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE LN_S EGREP ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB CPP CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE CXXCPP F77 FFLAGS ac_ct_F77 LIBTOOL ALSA_HSEARCH_R_TRUE ALSA_HSEARCH_R_FALSE SND_LIB_VERSION SND_LIB_MAJOR SND_LIB_MINOR SND_LIB_SUBMINOR SND_LIB_EXTRAVER LIBTOOL_VERSION_INFO VERSIONED_SYMBOLS_TRUE VERSIONED_SYMBOLS_FALSE BUILD_MIXER_TRUE BUILD_MIXER_FALSE BUILD_PCM_TRUE BUILD_PCM_FALSE BUILD_RAWMIDI_TRUE BUILD_RAWMIDI_FALSE BUILD_HWDEP_TRUE BUILD_HWDEP_FALSE BUILD_SEQ_TRUE BUILD_SEQ_FALSE BUILD_INSTR_TRUE BUILD_INSTR_FALSE BUILD_PCM_PLUGIN_TRUE BUILD_PCM_PLUGIN_FALSE BUILD_PCM_PLUGIN_COPY_TRUE BUILD_PCM_PLUGIN_COPY_FALSE BUILD_PCM_PLUGIN_LINEAR_TRUE BUILD_PCM_PLUGIN_LINEAR_FALSE BUILD_PCM_PLUGIN_ROUTE_TRUE BUILD_PCM_PLUGIN_ROUTE_FALSE BUILD_PCM_PLUGIN_MULAW_TRUE BUILD_PCM_PLUGIN_MULAW_FALSE BUILD_PCM_PLUGIN_ALAW_TRUE BUILD_PCM_PLUGIN_ALAW_FALSE BUILD_PCM_PLUGIN_ADPCM_TRUE BUILD_PCM_PLUGIN_ADPCM_FALSE BUILD_PCM_PLUGIN_RATE_TRUE BUILD_PCM_PLUGIN_RATE_FALSE BUILD_PCM_PLUGIN_PLUG_TRUE BUILD_PCM_PLUGIN_PLUG_FALSE BUILD_PCM_PLUGIN_MULTI_TRUE BUILD_PCM_PLUGIN_MULTI_FALSE BUILD_PCM_PLUGIN_SHM_TRUE BUILD_PCM_PLUGIN_SHM_FALSE BUILD_PCM_PLUGIN_FILE_TRUE BUILD_PCM_PLUGIN_FILE_FALSE BUILD_PCM_PLUGIN_NULL_TRUE BUILD_PCM_PLUGIN_NULL_FALSE BUILD_PCM_PLUGIN_SHARE_TRUE BUILD_PCM_PLUGIN_SHARE_FALSE BUILD_PCM_PLUGIN_METER_TRUE BUILD_PCM_PLUGIN_METER_FALSE BUILD_PCM_PLUGIN_HOOKS_TRUE BUILD_PCM_PLUGIN_HOOKS_FALSE BUILD_PCM_PLUGIN_LFLOAT_TRUE BUILD_PCM_PLUGIN_LFLOAT_FALSE BUILD_PCM_PLUGIN_LADSPA_TRUE BUILD_PCM_PLUGIN_LADSPA_FALSE BUILD_PCM_PLUGIN_DMIX_TRUE BUILD_PCM_PLUGIN_DMIX_FALSE BUILD_PCM_PLUGIN_DSHARE_TRUE BUILD_PCM_PLUGIN_DSHARE_FALSE BUILD_PCM_PLUGIN_DSNOOP_TRUE BUILD_PCM_PLUGIN_DSNOOP_FALSE BUILD_PCM_PLUGIN_ASYM_TRUE BUILD_PCM_PLUGIN_ASYM_FALSE BUILD_PCM_PLUGIN_IEC958_TRUE BUILD_PCM_PLUGIN_IEC958_FALSE BUILD_PCM_PLUGIN_SOFTVOL_TRUE BUILD_PCM_PLUGIN_SOFTVOL_FALSE BUILD_PCM_PLUGIN_EXTPLUG_TRUE BUILD_PCM_PLUGIN_EXTPLUG_FALSE BUILD_PCM_PLUGIN_IOPLUG_TRUE BUILD_PCM_PLUGIN_IOPLUG_FALSE LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar INSTALL_M4_TRUE INSTALL_M4_FALSE CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE LN_S EGREP ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB CPP CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE CXXCPP F77 FFLAGS ac_ct_F77 LIBTOOL ALSA_HSEARCH_R_TRUE ALSA_HSEARCH_R_FALSE SND_LIB_VERSION SND_LIB_MAJOR SND_LIB_MINOR SND_LIB_SUBMINOR SND_LIB_EXTRAVER LIBTOOL_VERSION_INFO VERSIONED_SYMBOLS_TRUE VERSIONED_SYMBOLS_FALSE BUILD_MIXER_TRUE BUILD_MIXER_FALSE BUILD_PCM_TRUE BUILD_PCM_FALSE BUILD_RAWMIDI_TRUE BUILD_RAWMIDI_FALSE BUILD_HWDEP_TRUE BUILD_HWDEP_FALSE BUILD_SEQ_TRUE BUILD_SEQ_FALSE BUILD_INSTR_TRUE BUILD_INSTR_FALSE BUILD_PCM_PLUGIN_TRUE BUILD_PCM_PLUGIN_FALSE BUILD_PCM_PLUGIN_COPY_TRUE BUILD_PCM_PLUGIN_COPY_FALSE BUILD_PCM_PLUGIN_LINEAR_TRUE BUILD_PCM_PLUGIN_LINEAR_FALSE BUILD_PCM_PLUGIN_ROUTE_TRUE BUILD_PCM_PLUGIN_ROUTE_FALSE BUILD_PCM_PLUGIN_MULAW_TRUE BUILD_PCM_PLUGIN_MULAW_FALSE BUILD_PCM_PLUGIN_ALAW_TRUE BUILD_PCM_PLUGIN_ALAW_FALSE BUILD_PCM_PLUGIN_ADPCM_TRUE BUILD_PCM_PLUGIN_ADPCM_FALSE BUILD_PCM_PLUGIN_RATE_TRUE BUILD_PCM_PLUGIN_RATE_FALSE BUILD_PCM_PLUGIN_PLUG_TRUE BUILD_PCM_PLUGIN_PLUG_FALSE BUILD_PCM_PLUGIN_MULTI_TRUE BUILD_PCM_PLUGIN_MULTI_FALSE BUILD_PCM_PLUGIN_SHM_TRUE BUILD_PCM_PLUGIN_SHM_FALSE BUILD_PCM_PLUGIN_FILE_TRUE BUILD_PCM_PLUGIN_FILE_FALSE BUILD_PCM_PLUGIN_NULL_TRUE BUILD_PCM_PLUGIN_NULL_FALSE BUILD_PCM_PLUGIN_SHARE_TRUE BUILD_PCM_PLUGIN_SHARE_FALSE BUILD_PCM_PLUGIN_METER_TRUE BUILD_PCM_PLUGIN_METER_FALSE BUILD_PCM_PLUGIN_HOOKS_TRUE BUILD_PCM_PLUGIN_HOOKS_FALSE BUILD_PCM_PLUGIN_LFLOAT_TRUE BUILD_PCM_PLUGIN_LFLOAT_FALSE BUILD_PCM_PLUGIN_LADSPA_TRUE BUILD_PCM_PLUGIN_LADSPA_FALSE BUILD_PCM_PLUGIN_DMIX_TRUE BUILD_PCM_PLUGIN_DMIX_FALSE BUILD_PCM_PLUGIN_DSHARE_TRUE BUILD_PCM_PLUGIN_DSHARE_FALSE BUILD_PCM_PLUGIN_DSNOOP_TRUE BUILD_PCM_PLUGIN_DSNOOP_FALSE BUILD_PCM_PLUGIN_ASYM_TRUE BUILD_PCM_PLUGIN_ASYM_FALSE BUILD_PCM_PLUGIN_IEC958_TRUE BUILD_PCM_PLUGIN_IEC958_FALSE BUILD_PCM_PLUGIN_SOFTVOL_TRUE BUILD_PCM_PLUGIN_SOFTVOL_FALSE BUILD_PCM_PLUGIN_EXTPLUG_TRUE BUILD_PCM_PLUGIN_EXTPLUG_FALSE BUILD_PCM_PLUGIN_IOPLUG_TRUE BUILD_PCM_PLUGIN_IOPLUG_FALSE BUILD_PCM_PLUGIN_MMAP_EMUL_TRUE BUILD_PCM_PLUGIN_MMAP_EMUL_FALSE LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -20211,7 +20211,7 @@ else
 pcm_plugins=""
 fi
 
-PCM_PLUGIN_LIST="copy linear route mulaw alaw adpcm rate plug multi shm file null share meter hooks lfloat ladspa dmix dshare dsnoop asym iec958 softvol extplug ioplug"
+PCM_PLUGIN_LIST="copy linear route mulaw alaw adpcm rate plug multi shm file null share meter hooks lfloat ladspa dmix dshare dsnoop asym iec958 softvol extplug ioplug mmap_emul"
 
 build_pcm_plugin="no"
 for t in $PCM_PLUGIN_LIST; do
@@ -20305,6 +20305,16 @@ if test x$build_pcm_adpcm = xyes; then
 else
   BUILD_PCM_PLUGIN_ADPCM_TRUE='#'
   BUILD_PCM_PLUGIN_ADPCM_FALSE=
+fi
+
+
+
+if test x$build_pcm_mmap_emul = xyes; then
+  BUILD_PCM_PLUGIN_MMAP_EMUL_TRUE=
+  BUILD_PCM_PLUGIN_MMAP_EMUL_FALSE='#'
+else
+  BUILD_PCM_PLUGIN_MMAP_EMUL_TRUE='#'
+  BUILD_PCM_PLUGIN_MMAP_EMUL_FALSE=
 fi
 
 
@@ -20910,6 +20920,14 @@ if test -z "${BUILD_PCM_PLUGIN_IOPLUG_TRUE}" && test -z "${BUILD_PCM_PLUGIN_IOPL
   { { echo "$as_me:$LINENO: error: conditional \"BUILD_PCM_PLUGIN_IOPLUG\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"BUILD_PCM_PLUGIN_IOPLUG\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
+if test -z "${BUILD_PCM_PLUGIN_MMAP_EMUL_TRUE}" && test -z "${BUILD_PCM_PLUGIN_MMAP_EMUL_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"BUILD_PCM_PLUGIN_MMAP_EMUL\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"BUILD_PCM_PLUGIN_MMAP_EMUL\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -21618,6 +21636,8 @@ s,@BUILD_PCM_PLUGIN_EXTPLUG_TRUE@,$BUILD_PCM_PLUGIN_EXTPLUG_TRUE,;t t
 s,@BUILD_PCM_PLUGIN_EXTPLUG_FALSE@,$BUILD_PCM_PLUGIN_EXTPLUG_FALSE,;t t
 s,@BUILD_PCM_PLUGIN_IOPLUG_TRUE@,$BUILD_PCM_PLUGIN_IOPLUG_TRUE,;t t
 s,@BUILD_PCM_PLUGIN_IOPLUG_FALSE@,$BUILD_PCM_PLUGIN_IOPLUG_FALSE,;t t
+s,@BUILD_PCM_PLUGIN_MMAP_EMUL_TRUE@,$BUILD_PCM_PLUGIN_MMAP_EMUL_TRUE,;t t
+s,@BUILD_PCM_PLUGIN_MMAP_EMUL_FALSE@,$BUILD_PCM_PLUGIN_MMAP_EMUL_FALSE,;t t
 s,@LIBOBJS@,$LIBOBJS,;t t
 s,@LTLIBOBJS@,$LTLIBOBJS,;t t
 CEOF
