New user folder check in
git-svn-id: svn://localhost/svn/uclinux-dist/trunk@1023 3e2a5524-39e8-4cb9-84a9-c49da69cba3a

diff --git a/user/wlan-ng/etc/wlan/shared b/user/wlan-ng/etc/wlan/shared
--- a/user/wlan-ng/etc/wlan/shared
+++ b/user/wlan-ng/etc/wlan/shared
@@ -1,3 +1,4 @@
+#!/bin/bash
 # etc/wlan/shared
 #
 # Copyright (C) 2002 AbsoluteValue Systems, Inc.  All Rights Reserved.
@@ -42,41 +43,93 @@
 #
 # --------------------------------------------------------------------
 
+if [ ! -n "$ECHO" ]; then
+	ECHO=echo
+fi
+
+if [ -x /sbin/modprobe ] ; then
+	MODPROBE=/sbin/modprobe
+else
+	${ECHO} "/sbin/modprobe not found."
+	exit 1
+fi
+
 if [ -x /sbin/wlanctl-ng ] ; then 
 	WLANCTL=/sbin/wlanctl-ng
 else
-	echo "wlanctl-ng not found."
+	${ECHO} "/sbin/wlanctl-ng not found."
 	exit 1
+fi
+
+if [ -x /sbin/wland ] ; then
+    WLAND=/sbin/wland
+else
+    ${ECHO} "/sbin/wland not found."
+    exit 1
+fi
+
+if [ -f /proc/sys/kernel/hotplug -a \
+	-x `cat /proc/sys/kernel/hotplug` -a \
+	-f /etc/hotplug/wlan.agent ] ; then
+	HAS_HOTPLUG=y
+else
+	HAS_HOTPLUG=n
 fi
 
 # Source the wlan configuration
 if [ -f /etc/wlan/wlan.conf ] ; then
 	. /etc/wlan/wlan.conf
 else
-	echo "/etc/wlan/wlan.conf not found."
+	${ECHO} "/etc/wlan/wlan.conf not found."
 	exit 0
 fi
+
+# Source NSD specific functions
+# nsd_fwload
+# nsd_mibset
+for i in /etc/wlan/shared.* ; do 
+	. $i
+done
 
 is_true ()
 {
 	# $1 == string containing a t/f indicator.
 
-	[ "$1" = "y" -o "$1" = "Y" -o "$1" = "yes" -o "$1" = "YES" ]
+	[ "$1" = "y" -o "$1" = "Y" -o "$1" = "yes" -o "$1" = "YES" \
+	  -o "$1" = "t" -o "$1" = "T" -o "$1" = "true" -o "$1" = "TRUE" ]
+}
+
+wlan_nsdname ()
+{
+	# $1 == wlandev
+	# Writes the given device's name to stdout
+	grep 'nsd name' /proc/net/p80211/$1/wlandev | sed -e 's/.*: \(.*\)_.*/\1/'
 }
 
 wlan_enable ()
 {
 	# $1 == wlandev
 
- 	#=======ENABLE IFSTATE=============================
- 	# Bring the device into its operable state
+	#=======ENABLE IFSTATE=============================
+	# Bring the device into its operable state
+
+	$MODPROBE $1
 	
 	# First, make sure the driver is loaded....
-	if ! ifconfig $1 2>&1 > /dev/null ; then
-		echo "Error: Device $1 does not seem to be present."
-		echo "Make sure you've inserted the appropriate"
-		echo "modules or that your modules.conf file contains"
-		echo "the appropriate aliase(s)."
+	if ! ifconfig $1 > /dev/null 2>&1 ; then
+		${ECHO} "Error: Device $1 does not seem to be present."
+		${ECHO} "Make sure you've inserted the appropriate"
+		${ECHO} "modules or that your modules.conf file contains"
+		${ECHO} "the appropriate aliase(s)."
+		return 1
+	fi
+
+	# Call the nsd script's fwload function, in case the card needs
+	# a firmware load, or could use an optional one.
+
+	nsdname=`wlan_nsdname $1`
+	if ! ${nsdname}_fwload $1 ; then
+		${ECHO} "Firmware failed to load for device $1"
 		return 1
 	fi
 
@@ -85,14 +138,17 @@ wlan_enable ()
 	if [ $? = 0 ] ; then
 		eval $result
 		if [ $resultcode != "success" ]; then
-			echo "Failed to enable the device, resultcode=" \
+			${ECHO} "Failed to enable the device, resultcode=" \
 				$resultcode "."
 			return 1
 		fi
 	else
-		echo "Failed to enable the device, exitcode=" $? "."
+		${ECHO} "Failed to enable the device, exitcode=" $? "."
 		return 1
 	fi
+
+	# Set any NSD specific MIBs
+	${nsdname}_mibset $1
 }
 
 wlan_user_mibs ()
@@ -106,11 +162,11 @@ wlan_user_mibs ()
 		if [ $? = 0 ] ; then
 			eval $result
 			if [ $resultcode != "success" ] ; then 
-				echo "Failed to set user MIB $i."
+				${ECHO} "Failed to set user MIB $i."
 				return 1
 			fi
 		else
-			echo "Failed to set user MIB $i."
+			${ECHO} "Failed to set user MIB $i."
 			return 1
 		fi
 	done
@@ -118,7 +174,7 @@ wlan_user_mibs ()
 
 wlan_source_config ()
 {
-	# $1 == wlandev 
+	# $1 == wlandev
 
 	# XXX what about stray singlequotes.
 	eval 'GOSSID="$SSID_'$1'"'
@@ -127,28 +183,30 @@ wlan_source_config ()
 
 wlan_source_config_for_ssid ()
 {
-	# $1 == ssid[:BSSID]
+	# $1 == ssid[:bssid]
+        # $2 == bssid (optional)
 
-	DesiredSSID="$1"
+        DesiredSSID="$1"
+        DesiredBSSID="$2"
 
-	if [ X"$1" != X"" ] ; then
-		token_ssid=`echo $1 | sed -ne 's/\(.*\)\(:..:..:..:..:..:..\).*/\1/p'`
-		token_bssid=`echo $1 | sed -ne 's/\(.*\):\(..:..:..:..:..:..\).*/\2/p'`
+        if [ -n "$2" ] ; then
+               token_ssid=`echo $1 | sed -ne 's/\(.*\)\(:..:..:..:..:..:..\).*/\1/p'`
+               token_bssid=`echo $1 | sed -ne 's/\(.*\):\(..:..:..:..:..:..\).*/\2/p'`
+	       if [ -n "$token_ssid" ] ; then
+		   DesiredSSID="$token_ssid"
+		   DesiredBSSID="$token_bssid"
+	       fi
+
 	fi
 
-        if [ X"$token_ssid" != X"" ] ; then
-                DesiredSSID="$token_ssid"
-                DesiredBSSID=$token_bssid
-        fi
-
-	if [ -f "/etc/wlan/wlancfg-$1" ] ; then
-		. "/etc/wlan/wlancfg-$1"
+	if [ -f "/etc/wlan/wlancfg-$DesiredSSID:$DesiredBSSID" ] ; then
+		. "/etc/wlan/wlancfg-$DesiredSSID:$DesiredBSSID"
 	elif [ -f "/etc/wlan/wlancfg-$DesiredSSID" ] ; then
 		. "/etc/wlan/wlancfg-$DesiredSSID"
 	else 
 
-		if [ X"$1" != X"" ] ; then
-			echo "Failed to open network config file /etc/wlan/wlancfg-$1, using default."
+		if [ -n "$1" ] ; then
+			${ECHO} "Failed to open network config file /etc/wlan/wlancfg-$1, using default."
 		fi
 
 		. "/etc/wlan/wlancfg-DEFAULT"
@@ -158,71 +216,32 @@ wlan_source_config_for_ssid ()
 wlan_disable ()
 {
 	# $1 == wlandev
+
 	$WLANCTL $1 lnxreq_ifstate ifstate=disable
 }	
-
-wlan_download ()
-{
-	result=`$WLANCTL $1 lnxreq_ifstate ifstate=disable`
-	if [ $? = 0 ] ; then
-		eval $result
-		if [ $resultcode != "success" ]; then
-			echo "Failed to disable the device, resultcode=" \
-				$resultcode "."
-			return 1
-		fi
-	else
-		echo "Failed to disable the device, exitcode=" $? "."
-		return 1
-	fi
-
-	result=`$WLANCTL $1 lnxreq_ifstate ifstate=fwload`
-	if [ $? = 0 ] ; then
-		eval $result
-		if [ $resultcode != "success" ]; then
-			echo "Failed to enable the device, resultcode=" \
-				$resultcode "."
-			return 1
-		fi
-	else
-		echo "Failed to enable the device, exitcode=" $? "."
-		return 1
-	fi
-
-	#=======DOWNLOAD======================================
-	# If the card needs code/data downloaded, do it.
-	if ! $WLAN_DOWNLOADER -r $WLAN_DLIMAGE $1 ; then
-		echo "Code/Data Download Failed."
-		return 1
-	fi
-
-	# re-enable the device.
-	wlan_enable $1
-}
 
 wlan_ssid_in_list ()
 {
 	# $1 == wlandev, $2 == ssid,  $3 == bssid
 
-	# XXX what about stray singlequotes.
-	eval 'GOSSID="$SSID_'$1'"'
-	
+  	eval 'GOSSID="$SSID_'$1'"'
+  	
 	# This "eval" hackery is to allow escapes in GOSSID...
 	cmd="for token in $GOSSID ; do
 		ssid_token=\`echo \"\$token\" | sed -ne 's/\(.*\)\(:..:..:..:..:..:..\).*/\1/p'\`
 		bssid_token=\`echo \"\$token\" | sed -ne 's/\(.*\):\(..:..:..:..:..:..\).*/\2/p'\`
-
-		if [ \"X\$ssid_token\" = X ] ; then
+  
+		if [ -z \"\$ssid_token\" ] ; then
 			ssid_token="\$token"
-		fi
-
-		if [ \"X\$bssid_token\" != X ] ; then
+  		fi
+  
+		if [ -n \"\$bssid_token\" ] ; then
 			if [ \"\$bssid_token\" = \"\$3\" ] ; then
-				return 0
-			fi
+  				return 0
+  			fi
 		elif [ \"\$2\" = \"\$ssid_token\" ] ; then
-			return 0	
-		fi
+  			return 0	
+  		fi
 	done"
 	eval "$cmd"
 
@@ -251,14 +270,14 @@ wlan_scan ()
 	# XXX what about stray singlequotes.
 	eval 'GOSSID="$SSID_'$1'"'
 
-	# if our list is null, then scan for anything!
-	
-	if [ "$GOSSID" = "" ] ; then
-		wlan_scan_one $1 
-		if [ $? = 0 ] ; then
-			return 0
-		fi
-	fi;
+	# kick off a quick scan with the broadcast SSID.
+	wlan_scan_one $1 '' '' n
+	if [ $? = 0  -a \
+	    "$GOSSID" = "" ] ; then
+	    # if successful and our ssid list is null, return.
+	    sleep 1
+	    return 0
+	fi	
 
 	# otherwise we walk through the list, and scan for eacn in turn.
 	# this "eval" hackery is to allow escapes in GOSSID
@@ -266,12 +285,13 @@ wlan_scan ()
 		ssid_token=\`echo \"\$token\" | sed -ne 's/\(.*\)\(:..:..:..:..:..:..\).*/\1/p'\`
 		bssid_token=\`echo \"\$token\" | sed -ne 's/\(.*\):\(..:..:..:..:..:..\).*/\2/p'\`
 
-		if [ \"X\$ssid_token\" = X ] ; then
+		if [ -z \"\$ssid_token\" ] ; then
 			ssid_token=\"\$token\"
 		fi
 
 		wlan_scan_one \$1 \"\$ssid_token\" \"\$bssid_token\"
 		if [ \$? = 0 ] ; then
+			sleep 1
 			return 0
 		fi
 	done"
@@ -279,55 +299,61 @@ wlan_scan ()
 
 	# We got to the end of the list.  Maybe try "any"
 	if is_true "$WLAN_ANY" ; then
-		wlan_scan_one $1 
+		wlan_scan_one $1
+		sleep 1
 		return $?
 	fi
 
-
+	sleep 1
 	return 1
 }
 
 
 wlan_scan_one ()
 {
-	# $1 == wlandev ( $2 == ssid, $3 == bssid ), optional
+	# $1 == wlandev, [ $2 == ssid, $3 == bssid, $4 == append ]
+
+    if [ -z "$4" ] ; then
+	append=true
+    else
+	append=false
+    fi
 
 	numbss=0
 
 	result=`$WLANCTL $1 dot11req_scan bsstype=any bssid=ff:ff:ff:ff:ff:ff \
-		scantype=both probedelay=0 channellist=$ChannelList ssid="$2" \
-		minchanneltime=$ChannelMinTime maxchanneltime=$ChannelMaxTime`
+		scantype=active probedelay=0 channellist=$ChannelList ssid="$2" \
+		minchanneltime=$ChannelMinTime maxchanneltime=$ChannelMaxTime append=$append`
 	eval $result
 	if [ $resultcode != 'success' ] ; then
-		echo "Scan failed ($resultcode) "
+		${ECHO} "Scan failed ($resultcode) "
 		return 1
 	fi
-	
+
+	## XXX if numbss == 0, repeat with $2 $3 $4?
+
 	i=0
 	bssfound=""
 
 	# walk through the results and do first-cut matching.
-
 	while [ $i -lt $numbss ] ; do
 		result=`$WLANCTL $1 dot11req_scan_results bssindex=$i`
 		eval $result
 
-		if [ X"$3" != X"" ] ; then
-			if [ "$3" = "$bssid" ] ; then
-				bssfound="$bssfound $i"
+		if [ -n "$3" ] ; then
+                        if [ "$3" = "$bssid" ] ; then
+                               bssfound="$bssfound $i"
 			fi
-		elif [ X"$2" = X"" ] ; then
+		elif [ -z "$2" ] ; then
 			# if our ssid is "", then we pick the first entry.
 			bssfound="$bssfound $i"
 		elif [ "$2" = "$ssid" ] ; then
-			bssfound="$bssfound $i"
-		else
 			bssfound="$bssfound $i"
 		fi
 		i=`expr $i + 1`
 	done
 
-	if [ "-$bssfound-" = "--" ]; then       # No BSSs found, bail.
+	if [ -z "$bssfound" ]; then	# No BSSs found, bail.
 		return 1
 	else
 		# Now find the closest
@@ -342,44 +368,48 @@ wlan_scan_one ()
 		done
 		result=`$WLANCTL $1 dot11req_scan_results bssindex=$bigbssindex`
 		eval $result
-
 		return 0
 	fi
 }
 
 wlan_wep ()
 {
+	# $1 == wlandev
+
 	#=======WEP===========================================
 	# Setup privacy
+	if [ ${dot11PrivacyInvoked:-"false"} = "false" ] ; then
+		return 0;
+	fi
+
 	result=`$WLANCTL $1 dot11req_mibget mibattribute=dot11PrivacyOptionImplemented`
 	if [ $? = 0 ] ; then
 		eval $result
 		eval $mibattribute
 	else
-		echo "dot11PrivacyOptionImplemented mibget failed."
+		${ECHO} "dot11PrivacyOptionImplemented mibget failed."
 		return 1
 	fi
 
-	if [ $dot11PrivacyOptionImplemented = "false" -a \
-	     $dot11PrivacyInvoked = "true" ] ; then
-		echo "Cannot enable privacy, dot11PrivacyOptionImplemented=false."
+	if [ $dot11PrivacyOptionImplemented = "false" ] ; then
+		${ECHO} "Cannot enable privacy, dot11PrivacyOptionImplemented=false."
 		return 1
 	fi
 
 	# Do we want host-based WEP?
 	result=`$WLANCTL $1 lnxreq_hostwep \
 	    decrypt="${lnxreq_hostWEPDecrypt:-false}"    \
-	    encrypt="${lnxreq_hostWEPEncrypt:-false}"  `
+	    encrypt="${lnxreq_hostWEPEncrypt:-false}"`
 
 	# set up the rest of the parametsrs.
 	if [ $dot11PrivacyOptionImplemented = "true" -a \
 	     $dot11PrivacyInvoked = "true" ] ; then
-		$WLANCTL $1 dot11req_mibset \
-			mibattribute=dot11WEPDefaultKeyID=$dot11WEPDefaultKeyID
-		$WLANCTL $1 dot11req_mibset \
-			mibattribute=dot11ExcludeUnencrypted=$dot11ExcludeUnencrypted
-		$WLANCTL $1 dot11req_mibset \
-			mibattribute=dot11PrivacyInvoked=$dot11PrivacyInvoked
+		result=`$WLANCTL $1 dot11req_mibset \
+			  mibattribute=dot11WEPDefaultKeyID=$dot11WEPDefaultKeyID `
+		result=`$WLANCTL $1 dot11req_mibset \
+			mibattribute=dot11ExcludeUnencrypted=$dot11ExcludeUnencrypted `
+		result=`$WLANCTL $1 dot11req_mibset \
+			mibattribute=dot11PrivacyInvoked=$dot11PrivacyInvoked`
 		if [ "${PRIV_GENSTR:-empty}" != "empty" ] ; then
 			if [ ${PRIV_KEY128:-"false"} = "false" ]; then
 				keys=`$PRIV_GENERATOR "$PRIV_GENSTR" 5`
@@ -388,31 +418,33 @@ wlan_wep ()
 			fi
 				knum=0
 			for i in $keys ; do
-				$WLANCTL $1 dot11req_mibset \
-				mibattribute=dot11WEPDefaultKey$knum=$i
-				knum=$[$knum + 1]
+				result=`$WLANCTL $1 dot11req_mibset \
+				mibattribute=dot11WEPDefaultKey$knum=$i`
+				knum=`expr $knum + 1`
 			done
 		else 
-			$WLANCTL $1 dot11req_mibset \
-			mibattribute=dot11WEPDefaultKey0=$dot11WEPDefaultKey0 
-			$WLANCTL $1 dot11req_mibset \
-			mibattribute=dot11WEPDefaultKey1=$dot11WEPDefaultKey1
-			$WLANCTL $1 dot11req_mibset \
-			mibattribute=dot11WEPDefaultKey2=$dot11WEPDefaultKey2
-			$WLANCTL $1 dot11req_mibset \
-			mibattribute=dot11WEPDefaultKey3=$dot11WEPDefaultKey3
+			result=`$WLANCTL $1 dot11req_mibset \
+			mibattribute=dot11WEPDefaultKey0=$dot11WEPDefaultKey0 `
+			result=`$WLANCTL $1 dot11req_mibset \
+			mibattribute=dot11WEPDefaultKey1=$dot11WEPDefaultKey1 `
+			result=`$WLANCTL $1 dot11req_mibset \
+			mibattribute=dot11WEPDefaultKey2=$dot11WEPDefaultKey2 `
+			result=`$WLANCTL $1 dot11req_mibset \
+			mibattribute=dot11WEPDefaultKey3=$dot11WEPDefaultKey3 `
 		fi
 	else
 		# disable wep explicitly.
-		$WLANCTL $1 dot11req_mibset \
-			mibattribute=dot11PrivacyInvoked=$dot11PrivacyInvoked
-		$WLANCTL $1 dot11req_mibset \
-			mibattribute=dot11ExcludeUnencrypted=false
+		result=`$WLANCTL $1 dot11req_mibset \
+			mibattribute=dot11PrivacyInvoked=$dot11PrivacyInvoked `
+		result=`$WLANCTL $1 dot11req_mibset \
+			mibattribute=dot11ExcludeUnencrypted=false `
 	fi
 }
 
 wlan_adhoc ()
 {
+	# $1 == wlandev
+
 	#=======IBSS STARTUP==================================
 	startcmd="$WLANCTL $1 dot11req_start "
 	startcmd="$startcmd ssid=$DesiredSSID"
@@ -428,26 +460,26 @@ wlan_adhoc ()
 	j=1
 	for i in $BASICRATES ; do
 		startcmd="$startcmd basicrate$j=$i"
-		j=$[j + 1]
+		j=`expr $j + 1`
 		done
 
 	j=1
 	for i in $OPRATES ; do
 		startcmd="$startcmd operationalrate$j=$i"
-		j=$[j + 1]
+		j=`expr $j + 1`
 	done
 
 	results=`$startcmd`	# Here's where it runs
 	if [ $? = 0 ]; then 
 		eval $results
 		if [ $resultcode != "success" ] ; then 
-			echo "IBSS not started, resultcode=$resultcode"
+			${ECHO} "IBSS not started, resultcode=$resultcode"
 			exit 1
 		else
-			echo "IBSS mode started."
+			${ECHO} "IBSS mode started."
 		fi
 	else
-		echo FAILED: $startcmd
+		${ECHO} FAILED: $startcmd
 		return 1
 	fi
 	WLAN_SCHEMESSID="$DesiredSSID"
@@ -455,15 +487,18 @@ wlan_adhoc ()
 
 wlan_infra ()
 {
+	# $1 == wlandev
+
 	#==== INFRASTRUCURE STARTUP===========================
 	# XXX TODO:  Grok DesiredBSSID
 
+	sleep 5
 	results=`$WLANCTL $1 lnxreq_autojoin \
 		"ssid=$DesiredSSID" \
 		authtype=${AuthType:="opensystem"} | sed 's/\([^=]*\)=\(.*\)/\1="\2"/'`
 	eval $results
 	if [ ${resultcode:-"failure"} != "success" ] ; then
-		echo 'error: Autojoin indicated failure!'
+		${ECHO} 'error: Autojoin indicated failure!'
 		return 1;
 	fi
 
@@ -472,23 +507,31 @@ wlan_infra ()
 
 wlan_dot11_join ()
 {
+	# $1 == wlandev
+
 	joincmd="$WLANCTL $1 dot11req_join bssid=$DesiredBSSID"
 	joincmd="$joincmd joinfailuretimeout=1"
 	
 	j=1
 	for i in $OPRATES ; do
 		joincmd="$joincmd operationalrate$j=$i"
-		j=$[j + 1]
+		j=`expr $j + 1`
 	done
 
 	results=`$joincmd`
 
 	eval $results
 	if [ ${resultcode:-"failure"} != "success" ] ; then
-		echo 'error:  dot11req_join failed!'
+		${ECHO} "$1: JOIN Failure"
+		${ECHO} "joincmd=$joincmd"
+		${ECHO} "results=$results"
 		return 1;
 	fi
+}
 
+wlan_dot11_auth_assoc ()
+{
+    # $1 == wlandev
 	if [ $bsstype = "infrastructure" ] ; then 
 		results=`$WLANCTL $1 dot11req_authenticate \
 				peerstaaddress=$DesiredBSSID \
@@ -496,7 +539,7 @@ wlan_dot11_join ()
 				authenticationfailuretimeout=2000`
 		eval $results
 		if [ ${resultcode:-"failure"} != "success" ] ; then
-			echo "error:  dot11req_authenticate failed, "\
+			${ECHO} "error:  dot11req_authenticate failed, "\
 				"resultcode=$resultcode"
 			return 1;
 		fi
@@ -504,7 +547,7 @@ wlan_dot11_join ()
 				listeninterval=1000 \
 				associatefailuretimeout=2000 `
 		if [ ${resultcode:-"failure"} != "success" ] ; then
-			echo 'error:  dot11req_associate failed!'
+			${ECHO} 'error:  dot11req_associate failed!'
 			return 1;
 		fi
 	fi
@@ -512,6 +555,8 @@ wlan_dot11_join ()
 
 wlan_set_ssid_schemefile ()
 {
+	# $1 == SSID
+
 	# Find the scheme file 
 	if [ -r /var/lib/misc/pcmcia-scheme ] ; then
 		# Debian
@@ -547,6 +592,7 @@ wlan_restore_schemefile ()
 {
 	# Find the scheme file 
 	if [ -r /var/lib/misc/pcmcia-scheme ] ; then
+		# Debian
 		WLAN_SCHEMEFILE="/var/lib/misc/pcmcia-scheme"
 	elif [ -d /var/state/pcmcia ] ; then
 		WLAN_SCHEMEFILE="/var/state/pcmcia/scheme"
@@ -562,6 +608,122 @@ wlan_restore_schemefile ()
 		cat $TMPFILE > $WLAN_SCHEMEFILE
 		rm -f $TMPFILE
 	else
-		echo "wlan_restore_schemefile: No wlan_scheme\*.tmp file found."
+		${ECHO} "wlan_restore_schemefile: No wlan_scheme\*.tmp file found."
 	fi
 }
+
+wlan_bring_it_up ()
+{
+    # $1 == wlandev
+    # $2 == non-null if wext enabled.
+
+    #=======ENABLE========================================
+    # Do we want to init the card at all?
+    eval 'WLAN_ENABLE=$ENABLE_'$1
+
+    if ! is_true $WLAN_ENABLE ; then
+	return 1
+    fi
+    
+    if wlan_enable $1 ; then
+	if [ -z "$2" ] ; then
+	    wlan_scan_and_join $1
+	    return $?
+	else
+	    ${ECHO} "Bypassing configuration due to wireless extensions"
+	fi	
+    else
+	return 1;
+    fi
+
+    return 1
+}
+
+wlan_scan_and_join ()
+{
+    #=======MAC STARTUP=========================================
+    wlan_supports_scan $1
+    if [ $? = 0 ] ; then
+	wlan_scan $1 
+	if [ $? = 0 ] ; then
+	    wlan_source_config_for_ssid "$ssid" "$bssid"
+	    
+	    wlan_user_mibs $1
+	    wlan_wep $1
+	    
+	    wlan_join $1
+	else
+	    if is_true $IS_ADHOC ; then     
+		# start an IBSS; we didn't find one.
+		wlan_adhoc $1
+	    else
+		return 1
+	    fi
+	fi
+    else
+	wlan_source_config $1
+	
+	wlan_user_mibs $1
+	wlan_wep $1
+	
+	if is_true $IS_ADHOC ; then     
+	    wlan_adhoc $1
+	else
+	    wlan_infra $1
+	fi
+    fi
+    
+    return $?
+}
+
+wlan_join ()
+{
+    # $1 == wlandev
+    grep 'autojoin' /proc/net/p80211/$1/wlandev > /dev/null
+    if [ $? = 0 ]; then
+	wlan_infra $1
+    else
+	wlan_dot11_join $1
+	wlan_dot11_auth_assoc $1
+    fi
+}
+
+start_wland ()
+{
+    $WLAND
+}
+
+stop_wland ()
+{
+    killall wland
+}
+
+tmpname ()
+{
+	# $1 == prefix
+	local i=0
+	local tname=$TMPDIR/${1}_$$
+	if [ -f ${tname}.tmp ] ; then
+		for i in 0 1 2 3 4 5 6 7 8 9 ; do
+			if [ ! -f ${tname}_${i}.tmp ] ; then
+				echo ${tname}_${i}.tmp 
+				return 0
+			fi
+		done
+	else
+		echo ${tname}.tmp
+	fi
+	return 0
+}
+
+source_procfile ()
+{
+	# $1 == procfile to source
+	local fname=`tmpname wlan_procfile`
+	cat "$1" > $fname
+	. $fname
+	rm -f $fname
+}
+
+# This is set by the Configure script as part of 'make install'
+#FIRMWARE_DIR="/usr/share/linux-wlan"
