[#2565] sync with upstream uClinux dist
git-svn-id: svn://localhost/svn/uclinux-dist/trunk@6122 3e2a5524-39e8-4cb9-84a9-c49da69cba3a

diff --git a/openswan/programs/_realsetup/_realsetup.in b/openswan/programs/_realsetup/_realsetup.in
--- a/openswan/programs/_realsetup/_realsetup.in
+++ b/openswan/programs/_realsetup/_realsetup.in
@@ -12,13 +12,15 @@
 # or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 # for more details.
 #
-# RCSID $Id: _realsetup.in,v 1.46.2.9 2006/05/05 18:49:45 ken Exp $
+# RCSID $Id: _realsetup.in,v 1.46.2.17 2007-11-05 17:05:48 paul Exp $
 
 me='ipsec setup'		# for messages
 
 # Misc. paths (some of this should perhaps be overrideable from ipsec.conf).
 plutopid=/var/run/pluto/pluto.pid
 plutoctl=/var/run/pluto/pluto.ctl
+rundir=/var/run/pluto
+subsysdir=/var/lock/subsys
 subsyslock=/var/lock/subsys/ipsec
 lock=/var/run/pluto/ipsec_setup.pid
 info=/var/run/pluto/ipsec.info
@@ -143,7 +145,8 @@ then
 	# interfaces to parse through,  much quicker to go
 	# direct to the source
 	#
-    KILLKLIPS='ifl=`grep -v NULL /proc/net/ipsec_tncfg 2> /dev/null | sed -n -e "/^ipsec/s/ .*//p" ` ;
+	KILLKLIPS='ifl=`grep -v NULL /proc/net/ipsec_tncfg 2> /dev/null | sed -n -e "/^ipsec/s/ .*//p" ` ;
+
 	test "X$ifl" != "X" &&
 	for i in  $ifl ;
 	do
@@ -152,13 +155,13 @@ then
 	done ;
 	test -r /proc/net/ipsec_klipsdebug && ipsec klipsdebug --none ;
 	test -d /proc/net/ipsec/eroute && ipsec eroute --clear ;
-	test -d /proc/net/ipsec/spi && ipsec spi --clear'
+	test -d /proc/net/ipsec/spi && ipsec spi --clear ;
 	lsmod 2>&1 | grep "^ipsec" > /dev/null && rmmod ipsec ; 
 	for ifname in `ls /proc/sys/net/ipv4/conf/|grep ipsec`; do
         	for ipaddr in `ip addr list dev $ifname | sed -n "/inet/ s/.*inet \(.*\) brd.*/\1/p"`; do
-                	ip addr del "$ipaddr" dev "$ifname"
-		done
-	done 
+                	ip addr del "$ipaddr" dev "$ifname" ;
+		done ;
+	done '
 fi
 
 if $netkey
@@ -182,8 +185,8 @@ case "$1" in
   start|--start|_autostart)
 	# First, does it seem to be going already?
 	perform test ! -f $lock "||" "{" \
-		echo "\"Openswan IPsec apparently already running, start aborted\"" ";" \
-		exit 1 ";" \
+		echo "\"Openswan IPsec apparently already active, start aborted\"" ";" \
+		exit 0 ";" \
 		"}"
 
 	# announcement
@@ -196,6 +199,8 @@ case "$1" in
 
 	# preliminaries
 	perform rm -f $lock
+	mkdir -p $rundir > /dev/null 2>/dev/null
+	mkdir -p $subsysdir > /dev/null 2>/dev/null
 
 	# the meaning of $$ at a different runtime is questionable!
 	perform echo '$$' ">" $lock
@@ -207,7 +212,7 @@ case "$1" in
 
 	perform ">" $info
 
-	# overridemtu is ignored on 2.6, so warn the user.
+	# overridemtu is ignored on NETKEY, so warn the user.
 	if $netkey
 	then
         	if test $IPSECoverridemtu
@@ -303,9 +308,9 @@ case "$1" in
 			status=0 ";" \
 			. $info ";" \
 		else \
-			echo "\"stop ordered, but IPsec does not appear to be running!\"" ";" \
+			echo "\"stop ordered, but IPsec appear to be stopped already!\"" ";" \
 			echo "\"doing cleanup anyway...\"" ";" \
-			status=1 ";" \
+			status=0 ";" \
 		fi
 	if test " $IPSECforwardcontrol" = " yes"
 	then
@@ -322,7 +327,7 @@ case "$1" in
 	fi
 
 	perform test -f $plutopid "&&" "{" \
-		if ps -p '`' cat $plutopid '`' ">" /dev/null ";" \
+		if test -d '/proc/`' cat $plutopid '`' ">" /dev/null ";" \
 		then \
 			ipsec whack --shutdown "|" grep -v "^002" ";" \
 			sleep 1 ";" \
@@ -360,7 +365,7 @@ case "$1" in
 	if test " $IPSEC_setupflags" != " "
 	then
 		echo "$me $1 does not support $IPSEC_setupflags"
-		exit 1
+		exit 4
 	fi
 
 	if test -f $info
@@ -380,12 +385,14 @@ case "$1" in
 
 	if test -s $plutopid
 	then
-		if ps -p `cat $plutopid` >/dev/null
+		if test -d /proc/`cat $plutopid 2> /dev/null` >/dev/null
 		then
 			plutokind=normal
 		elif ps -C pluto >/dev/null
 		then
 			plutokind=illicit
+		else
+			plutokind=dead
 		fi
 	elif ps -C pluto >/dev/null
 	then
@@ -420,31 +427,13 @@ case "$1" in
 		lk26sec=yes
 	fi
 
-	if test "$haslock"
+	if test "$hassublock" -a "$haslock" -a "$plutokind" = "normal" -a \( "$klips" = "yes" -o "$lk26sec" = "yes" \)  -a "$hasinfo"
 	then
-		echo "IPsec running"  " - pluto pid: `cat $plutopid`"
-		# might not be a subsystem lock dir, ignore that issue
-		if test "$plutokind" = "normal" -a \( "$klips" = "yes" -o "$lk26sec" = "yes" \)  -a "$hasinfo"
-		then
-			echo "pluto pid `cat $plutopid`"
-                        case "$eroutes" in
-                        0)      echo "No tunnels up"    ;;
-                        *)      echo "$eroutes tunnels up"      ;;
-                        esac
-			exit 0
-		fi
-		echo "but..."
-		if test "$plutokind" != "normal"
-		then
-			echo "$plutokind Pluto running" " - pluto pid: `cat $plutopid`"
-		fi
-		if test ! "$hasinfo"
-		then
-			echo "$info file missing!"
-		fi
-		case $klips in
-		maybe)	echo "KLIPS module is not loaded!"	;;
-		none)	echo "no KLIPS in kernel!"		;;
+		echo "IPsec running"  " - pluto pid: `cat $plutopid 2>/dev/null`"
+		echo "pluto pid `cat $plutopid`"
+		case "$eroutes" in
+			0)      echo "No tunnels up"    ;;
+			*)      echo "$eroutes tunnels up"      ;;
 		esac
 		if test "$eroutes"
 		then
@@ -453,16 +442,18 @@ case "$1" in
 				echo "some eroutes exist"
 			fi
 		fi
+		exit 0
 	else
 		echo "IPsec stopped"
 		if test ! "$hassublock" -a ! "$hasinfo" -a "$plutokind" = "no" -a "$eroutes" -eq 0
 		then
-			exit 0
+			exit 3
 		fi
 		echo "but..."
 		if test "$hassublock"
 		then
 			echo "has subsystem lock ($subsyslock)!"
+			exit 2
 		fi
 		if test "$hasinfo"
 		then
@@ -470,17 +461,17 @@ case "$1" in
 		fi
 		if test "$plutokind" != "no"
 		then
-			echo "An ${plutokind} Pluto is running?"
+			echo "An ${plutokind} Pluto is active?"
 		fi
 		if test "$eroutes" -gt 0
 		then
 			echo "some (${eroutes}) eroutes exist!"
 		fi
-		exit 1
 	fi
 	# todo: ipsec verify --quiet that only shows problems
-	/usr/sbin/ipsec verify;
-	exit $?;
+	#/usr/sbin/ipsec verify;
+	#exit $?;
+	exit 4
 	;;
 
   --version)
