[#2565] pull Documentation/bin/freeswan/openswan updates from upstream uclinux-dist
git-svn-id: svn://localhost/svn/uclinux-dist/trunk@7145 3e2a5524-39e8-4cb9-84a9-c49da69cba3a

diff --git a/openswan/programs/_realsetup/_realsetup.in b/openswan/programs/_realsetup/_realsetup.in
--- a/openswan/programs/_realsetup/_realsetup.in
+++ b/openswan/programs/_realsetup/_realsetup.in
@@ -12,38 +12,37 @@
 # or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 # for more details.
 #
-# RCSID $Id: _realsetup.in,v 1.46.2.17 2007-11-05 17:05:48 paul Exp $
 
 me='ipsec setup'		# for messages
 
 # Misc. paths (some of this should perhaps be overrideable from ipsec.conf).
 plutopid=/var/run/pluto/pluto.pid
 plutoctl=/var/run/pluto/pluto.ctl
-rundir=/var/run/pluto
-subsysdir=/var/lock/subsys
 subsyslock=/var/lock/subsys/ipsec
 lock=/var/run/pluto/ipsec_setup.pid
 info=/var/run/pluto/ipsec.info
 sysflags=/proc/sys/net/ipsec
 modules=/proc/modules
-ipforward=/proc/sys/net/ipv4/ip_forward
 ipsecversion=/proc/net/ipsec_version
 kamepfkey=/proc/net/pfkey
 
 # make sure output of (e.g.) ifconfig is in English
 unset LANG LANGUAGE LC_ALL LC_MESSAGES
 
-# check we were called properly
-if test " $IPSEC_confreadsection" != " setup"
+if test `ip addr list|grep -c cipsec` -ne 0
 then
-	echo "$me: $0 must be called by ipsec_setup" >&2
+	echo "Cisco IPSec client is already loaded, aborting! (cipsec# device found)"
 	exit 1
 fi
+
 # defaults for "config setup" items
 
+#######################################################################
+### WARNING: some of these defaults are set using addconn --configsetup
+###          This will go away!
+#######################################################################
 IPSECinterfaces=${IPSECinterfaces:-%defaultroute}
 	if test " $IPSECinterfaces" = " %none" ; then IPSECinterfaces= ; fi
-# IPSECforwardcontrol	"no"
 # IPSECsyslog	"daemon.error"
 # IPSECklipsdebug	"none"
 # IPSECplutodebug	"none"
@@ -55,27 +54,43 @@ IPSECplutowait=${IPSECplutowait:-no}
 # IPSECpostpluto	""
 # IPSECfragicmp	"yes"
 # IPSEChidetos	"yes"
-IPSECrp_filter=${IPSECrp_filter:-0}
 IPSECuniqueids=${IPSECuniqueids:-yes}
+IPSECdisable_port_floating=${IPSECdisable_port_floating:-no}
 IPSECcrlcheckinterval=${IPSECcrlcheckinterval:-0}
 IPSECprotostack=${IPSECprotostack:-auto}
 # IPSECoverridemtu	""
 
+# set defaults
+mast=false
+klips=false
+netkey=false
+
 # which kernel are we using?
 case $IPSECprotostack in
 auto)
-    if test -f $kamepfkey
+    # for now, you can not auto-select mast
+    #if test -f /proc/sys/net/ipsec/debug_mast
+    if false
+    then
+    	netkey=false; klips=false; mast=true;
+    elif test -f $kamepfkey
 	then
 	    netkey=true; klips=false;
 	else
 	    netkey=false; klips=true;
     fi;;
     
-klips)  netkey=false; klips=true;;
-netkey) netkey=true;  klips=false;;
-none)   netkey=false; klips=false;;
+klips)  netkey=false; klips=true;  mast=false;;
+mast)   netkey=false; klips=false; mast=true;;
+netkey) 
+        if test \! -f $kamepfkey
+        then
+                @MODPROBE@ af_key;
+	fi;
+	netkey=true;  klips=false; mast=false;;
+none)   netkey=false; klips=false; mast=false;;
+nostack) netkey=false; klips=false; mast=false;;
 esac
-
 
 # Shall we trace?
 execute="true"
@@ -116,7 +131,7 @@ manualconns() {
 	fi
 
 	# search for things to "ipsec manual --up": auto == "manual"
-	eval `ipsec _confread --varprefix MANUALSTART --search auto manual`
+	eval `ipsec addconn --varprefix MANUALSTART --search auto manual`
 	if test " $MANUALSTART_confreadstatus" != " "
 	then
 		echo "auto=manual search: $MANUALSTART_confreadstatus"
@@ -138,30 +153,26 @@ LOGONLY="logger -p $IPSECsyslog -t ipsec_setup"
 # within another sequence (for plutorun).
 # Luckily there are NO substitutions in it.
 
+KILLKLIPS=":"
+
 if $klips
 then
-	#
-	# don't use ifconfig here,  there may be thousands of
-	# interfaces to parse through,  much quicker to go
-	# direct to the source
-	#
-	KILLKLIPS='ifl=`grep -v NULL /proc/net/ipsec_tncfg 2> /dev/null | sed -n -e "/^ipsec/s/ .*//p" ` ;
-
-	test "X$ifl" != "X" &&
-	for i in  $ifl ;
-	do
-		ifconfig $i down ;
+        #
+        # don't use ifconfig here,  there may be thousands of
+        # interfaces to parse through,  much quicker to go
+        # direct to the source
+        #
+    KILLKLIPS='ifl=`grep -v NULL /proc/net/ipsec_tncfg 2> /dev/null | sed -n -e "/^ipsec/s/ .*//p" ` ;
+        test "X$ifl" != "X" &&
+        for i in  $ifl ;
+        do
+		ip link set $i down ;
+		ip addr flush dev $i ;
 		ipsec tncfg --detach --virtual $i ;
 	done ;
 	test -r /proc/net/ipsec_klipsdebug && ipsec klipsdebug --none ;
 	test -d /proc/net/ipsec/eroute && ipsec eroute --clear ;
-	test -d /proc/net/ipsec/spi && ipsec spi --clear ;
-	lsmod 2>&1 | grep "^ipsec" > /dev/null && rmmod ipsec ; 
-	for ifname in `ls /proc/sys/net/ipv4/conf/|grep ipsec`; do
-        	for ipaddr in `ip addr list dev $ifname | sed -n "/inet/ s/.*inet \(.*\) brd.*/\1/p"`; do
-                	ip addr del "$ipaddr" dev "$ifname" ;
-		done ;
-	done '
+	test -d /proc/net/ipsec/spi && ipsec spi --clear'
 fi
 
 if $netkey
@@ -202,6 +213,14 @@ case "$1" in
 	mkdir -p $rundir > /dev/null 2>/dev/null
 	mkdir -p $subsysdir > /dev/null 2>/dev/null
 
+	for f in /dev/random /dev/urandom
+	do
+		perform test -r $f "||" "{" \
+			echo "\"...unable to start Openswan IPsec, no $f!\"" ";" \
+			exit 1 ";" \
+			"}"
+        done
+
 	# the meaning of $$ at a different runtime is questionable!
 	perform echo '$$' ">" $lock
 	perform test -s $lock "||" "{" \
@@ -212,46 +231,54 @@ case "$1" in
 
 	perform ">" $info
 
-	# overridemtu is ignored on NETKEY, so warn the user.
+	# overridemtu is ignored on 2.6, so warn the user.
+	# no longer warn about %defaultroute, because it has some use on
+	# netkey for orienting ourselves when using left=%defaultroute
 	if $netkey
 	then
         	if test $IPSECoverridemtu
         	then
                 	echo "WARNING: overridemtu= is ignored when using the NETKEY stack"
         	fi
+
+
+		perform ipsec _startnetkey \
+				--info $info \
+				--debug "\"$IPSECklipsdebug\"" \
+				--omtu "\"$IPSECoverridemtu\"" \
+				--fragicmp "\"$IPSECfragicmp\"" \
+				--hidetos "\"$IPSEChidetos\"" \
+				--log "\"$IPSECsyslog\"" \
+				$IPSECinterfaces "||" \
+			"{" rm -f $lock ";" exit 1 ";" "}"
 	fi
 
+	if $klips
+	then
+		# here we go
+		perform ipsec _startklips \
+				--info $info \
+				--debug "\"$IPSECklipsdebug\"" \
+				--omtu "\"$IPSECoverridemtu\"" \
+				--fragicmp "\"$IPSECfragicmp\"" \
+				--hidetos "\"$IPSEChidetos\"" \
+				--log "\"$IPSECsyslog\"" \
+				$IPSECinterfaces "||" \
+			"{" rm -f $lock ";" exit 1 ";" "}"
 
-	# here we go
-	perform ipsec _startklips \
-			--info $info \
-			--debug "\"$IPSECklipsdebug\"" \
-			--omtu "\"$IPSECoverridemtu\"" \
-			--fragicmp "\"$IPSECfragicmp\"" \
-			--hidetos "\"$IPSEChidetos\"" \
-			--rpfilter "\"$IPSECrp_filter\"" \
-			--log "\"$IPSECsyslog\"" \
-			$IPSECinterfaces "||" \
-		"{" rm -f $lock ";" exit 1 ";" "}"
+# Paul: Shouldn't the below tests be outside the klips test?
 
-	perform test -f $ipsecversion "||" \
-		test -f $kamepfkey "||" "{" \
-		echo "\"OOPS, should have aborted!  Broken shell!\"" ";" \
-		exit 1 ";" \
-		"}"
+		perform test -f $ipsecversion "||" \
+			test -f $kamepfkey "||" "{" \
+			echo "\"OOPS, should have aborted!  Broken shell!\"" ";" \
+			exit 1 ";" \
+			"}"
+	fi
 
 	# misc pre-Pluto setup
 
 	perform test -d `dirname $subsyslock` "&&" touch $subsyslock
 
-	if test " $IPSECforwardcontrol" = " yes"
-	then
-		perform grep '"^0"' $ipforward ">" /dev/null "&&" "{" \
-			echo "\"enabling IP forwarding:\"" "|" $LOGONLY ";" \
-			echo "\"ipforwardingwas=$fw\"" ">>" $info ";" \
-			echo 1 ">" $ipforward ";" \
-			"}"
-	fi
 	manualconns
 
 	plutorestartoncrash=""
@@ -270,6 +297,7 @@ case "$1" in
 		perform ipsec _plutorun $re \
 			--debug "\"$IPSECplutodebug\"" \
 			--uniqueids "\"$IPSECuniqueids\"" \
+			--force_busy "\"$IPSECforce_busy\"" \
 			--nocrsend "\"$IPSECnocrsend\"" \
 			--strictcrlpolicy "\"$IPSECstrictcrlpolicy\"" \
 			--nat_traversal "\"$IPSECnat_traversal\"" \
@@ -308,17 +336,10 @@ case "$1" in
 			status=0 ";" \
 			. $info ";" \
 		else \
-			echo "\"stop ordered, but IPsec appear to be stopped already!\"" ";" \
+			echo "\"stop ordered, but IPsec appears to be already stopped!\"" ";" \
 			echo "\"doing cleanup anyway...\"" ";" \
 			status=0 ";" \
 		fi
-	if test " $IPSECforwardcontrol" = " yes"
-	then
-		perform test "\"X\$ipforwardingwas\"" = "\"X0\"" "&&" "{" \
-			echo "\"disabling IP forwarding:\"" "|" $LOGONLY ";" \
-			echo 0 ">" $ipforward ";" \
-			"}"
-	fi
 
 	if [ -f /var/run/pluto.pid -a ! -f /var/run/pluto/pluto.pid ]
 	then
@@ -348,10 +369,12 @@ case "$1" in
 
 	# When we exit we clean up (remove) the modules we are using, even the kame'ish ones
 	if test -e ${kamepfkey}; then
-		lsmod 2>&1 | grep "^xfrm4_tunnel" > /dev/null && rmmod -s xfrm4_tunnel
-		lsmod 2>&1 | grep "^af_key" > /dev/null && rmmod -s af_key
-		# old name for xfrm4_tunnel
-		lsmod 2>&1 | grep "^xfrm_user" > /dev/null && rmmod -s xfrm_user
+		for mod in xfrm6_tunnel xfrm6_mode_tunnel xfrm6_mode_beet xfrm6_mode_ro \
+			xfrm6_mode_transport xfrm4_mode_transport xfrm4_mode_tunnel  xfrm_user \
+			xfrm4_tunnel xfrm4_mode_beet esp4 esp6 ah4 ah6 ipcomp ipcomp6 af_key
+		    do
+			lsmod 2>&1 | grep "^$mod" > /dev/null && rmmod  $mod
+		    done
 	fi 
 
 	perform test -d `dirname $subsyslock` "&&" rm -f $subsyslock
@@ -408,9 +431,8 @@ case "$1" in
 			eroutes=`wc -l < /proc/net/ipsec_eroute 2> /dev/null | sed s/\ //g`
 		fi
 	else
-		eroutes=`ipsec auto --status 2> /dev/null | grep -i "ipsec sa established" | wc -l | sed s/\ //g`
+		eroutes=`ipsec eroute 2> /dev/null | wc -l | sed s/\ //g`
 	fi
-
 
 	if test -r $ipsecversion
 	then
@@ -467,6 +489,7 @@ case "$1" in
 		then
 			echo "some (${eroutes}) eroutes exist!"
 		fi
+		exit 1
 	fi
 	# todo: ipsec verify --quiet that only shows problems
 	#/usr/sbin/ipsec verify;
diff --git a/openswan/programs/_startklips/_startklips.in b/openswan/programs/_startklips/_startklips.in
--- a/openswan/programs/_startklips/_startklips.in
+++ b/openswan/programs/_startklips/_startklips.in
@@ -1,6 +1,7 @@
 #!/bin/sh
 # KLIPS startup script
 # Copyright (C) 1998, 1999, 2001, 2002  Henry Spencer.
+# Copyright (C) 2006, 2007  Paul Wouters <paul@xelerance.com>
 # 
 # This program is free software; you can redistribute it and/or modify it
 # under the terms of the GNU General Public License as published by the
@@ -12,19 +13,14 @@
 # or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 # for more details.
 #
-# RCSID $Id: _startklips.in,v 1.43.4.13 2007-09-05 02:58:55 paul Exp $
 
 me='ipsec _startklips'		# for messages
 
 # KLIPS-related paths
 sysflags=/proc/sys/net/ipsec
 modules=/proc/modules
-# full rp_filter path is $rpfilter1/interface/$rpfilter2
-rpfilter1=/proc/sys/net/ipv4/conf
-rpfilter2=rp_filter
-# %unchanged or setting (0, 1, or 2)
-rpfiltercontrol=0
-ipsecversion=/proc/net/ipsec_version
+netkey=/proc/net/pfkey
+ipsecversion=/proc/net/ipsec/version
 moduleplace=/lib/modules/`uname -r`/kernel/net/ipsec
 bareversion=`uname -r | sed -e 's/\.nptl//' | sed -e 's/^\(2\.[0-9]\.[1-9][0-9]*-[1-9][0-9]*\(\.[0-9][0-9]*\)*\(\.x\)*\).*$/\1/'`
 moduleinstplace=/lib/modules/$bareversion/kernel/net/ipsec
@@ -37,10 +33,46 @@ case $bareversion in
 		;;
 esac
 
-klips=true
-netkey=/proc/net/pfkey
+# since netkey now calls _startnetkey, we know we're called to use klips or mast.
+# so if we find netkey, try to unload it or die
+if test -f $netkey
+then
+	echo "Warning: found NETKEY stack loaded"
+	echo -n Trying to unload all NETKEY modules:
+                for mod in xfrm6_tunnel xfrm6_mode_tunnel xfrm6_mode_beet xfrm6_mode_ro \
+                        xfrm6_mode_transport xfrm4_mode_transport xfrm4_mode_tunnel \
+                        xfrm4_tunnel xfrm4_mode_beet esp4 esp6 ah4 ah6 ipcomp ipcomp6 af_key xfrm_user
+                   do
+                        echo -n "$mod "
+                        rmmod -a $mod 2> /dev/null
+                   done
+                echo
+	if test -f $netkey
+	then
+		echo "\nFAILURE to unload NETKEY modules. Use protostack=netkey or recompile kernel without builtin NETKEY support"
+		exit 1
+	fi
+fi
 
-info=/dev/null
+# which kernel are we using?
+case $IPSECprotostack in
+klips)   klips=true;  mast=false;;
+mast)    klips=false; mast=true;;
+none)    klips=false; mast=false;;
+nostack) klips=false; mast=false;;
+*|auto)
+    #if test -f /proc/sys/net/ipsec/debug_mast
+    if false
+    then
+	klips=false; mast=true;
+	else
+	    klips=true; mast=false;
+    fi;;
+esac
+
+#should this not be /var/run/pluto/ipsec.info?
+#info=/dev/null
+info=/var/run/pluto/ipsec.info
 log=daemon.error
 for dummy
 do
@@ -51,13 +83,23 @@ do
 	--omtu)		omtu="$2" ; shift	;;
 	--fragicmp)	fragicmp="$2" ; shift	;;
 	--hidetos)	hidetos="$2" ; shift	;;
-	--rpfilter)	rpfiltercontrol="$2" ; shift	;;
 	--)	shift ; break	;;
 	-*)	echo "$me: unknown option \`$1'" >&2 ; exit 2	;;
 	*)	break	;;
 	esac
 	shift
 done
+
+if $klips
+then
+    logger -p $log -t ipsec_setup "Using KLIPS/legacy stack"
+elif $mast
+then
+    logger -p $log -t ipsec_setup "Using KLIPS/mast stack"
+else
+    logger -p $log -t ipsec_setup "NOT using any IPsec stack - no real IPsec SA's will be created"
+fi
+
 
 
 
@@ -137,20 +179,13 @@ klipsinterface() {
 	else
 		mtu=
 	fi
-	if $klips
-	then
-		echo "KLIPS $virt on $phys $addr/$mask $type $otheraddr $mtu" | logonly
-	else
-		echo "NETKEY on $phys $addr/$mask $type $otheraddr $mtu" | logonly
-	fi
+	echo "KLIPS $virt on $phys $addr/$mask $type $otheraddr $mtu" | logonly
+
 	if $klips
 	then
 		# attach the interface and bring it up
 		ipsec tncfg --attach --virtual $virt --physical $phys
-		# busybox does not like "inet" keyword in ifconfiga
-		# see http://busybox.net/bugs/view.php?id=752
-		# ifconfig $virt inet $addr $type $otheraddr netmask $mask $mtu
-		ifconfig $virt $addr $type $otheraddr netmask $mask $mtu
+		ifconfig $virt inet $addr $type $otheraddr netmask $mask $mtu
 	fi
 
 	# if %defaultroute, note the facts
@@ -172,39 +207,6 @@ klipsinterface() {
 		echo '#dr: no default route' >>$info
 	fi
 
-	# check for rp_filter trouble
-	checkif $phys			# thought to be a problem only on phys
-}
-
-# check an interface for problems
-checkif() {
-	$klips || return 0
-	rpf=$rpfilter1/$1/$rpfilter2
-	if test -f $rpf
-	then
-		r="`cat $rpf`"
-		if test " $r" != " 0"
-		then
-			case "$r-$rpfiltercontrol" in
-			0-%unchanged|0-0|1-1|2-2)
-				# happy state
-				;;
-			*-%unchanged)
-				echo "WARNING: $1 has route filtering turned on; KLIPS may not work ($rpf is $r)"
-				;;
-			[012]-[012])
-				echo "WARNING: changing route filtering on $1 (changing $rpf from $r to $rpfiltercontrol)"
-				echo "$rpfiltercontrol" >$rpf
-				;;
-			[012]-*)
-				echo "ERROR: unknown rpfilter setting: $rpfiltercontrol"
-				;;
-			*)
-				echo "ERROR: unknown $rpf value $r"
-				;;
-			esac
-		fi
-	fi
 }
 
 # interfaces=%defaultroute:  put ipsec0 on top of default route's interface
@@ -216,18 +218,17 @@ defaultinterface() {
 		echo "no default route, %defaultroute cannot cope!!!"
 		exit 1
 	fi
-	if test `echo " $phys" | wc -l` -gt 1
-	then
-		echo "multiple default routes, %defaultroute cannot cope!!!"
-		exit 1
-	fi
 	next=`netstat -nr |
 		awk '$1 == "0.0.0.0" && $3 == "0.0.0.0" { print $2; exit 0 }'`
-	if [ "$next" = "0.0.0.0" ] ; then
-		next=`ip addr list $phys | grep -E "^ +inet6*.*scope global $phys" |
-			awk '{ f($3=="peer")print $4; else print $2 }' | awk -F / '{ print $1 }'`
+        if test `echo " $phys" | wc -l` -gt 1
+        then
+                echo "multiple default routes, %defaultroute using: $next"
+        fi
+
+	if $klips
+	then
+	    klipsinterface "ipsec0=$phys" $next
 	fi
-	klipsinterface "ipsec0=$phys" $next
 }
 
 # log only to syslog, not to stdout/stderr
@@ -235,39 +236,6 @@ logonly() {
 	logger -p $log -t ipsec_setup
 }
 
-# sort out which module is appropriate, changing it if necessary
-setmodule() {
-	if [ -e /proc/kallsyms ]
-	then
-		kernelsymbols="/proc/kallsyms";
-		echo "calcgoo: warning: 2.6 kernel with kallsyms not supported yet"
-	else
-		kernelsymbols="/proc/ksyms";
-	fi	
-        wantgoo="`ipsec calcgoo $kernelsymbols`"
-        module=$moduleplace/$modulename
-        if test -f $module
-        then
-                goo="`nm -ao $module | ipsec calcgoo`"
-                if test " $wantgoo" = " $goo"
-                then
-                        return          # looks right
-                fi
-        fi
-        if test -f $moduleinstplace/$wantgoo
-        then
-                echo "modprobe failed, but found matching template module $wantgoo."
-                echo "Copying $moduleinstplace/$wantgoo to $module."
-                rm -f $module
-                mkdir -p $moduleplace
-                cp -p $moduleinstplace/$wantgoo $module
-                # "depmod -a" gets done by caller
-        fi
-}
-
-
-
-# main line
 
 # load module if possible
 if test -f $ipsecversion && test -f $netkey
@@ -276,69 +244,32 @@ then
     echo "FATAL ERROR: Both KLIPS and NETKEY IPsec code is present in kernel"
     exit
 fi
-if test ! -f $ipsecversion && test ! -f $netkey && @MODPROBE@ -q ipsec
+if test ! -f $ipsecversion && test ! -f $netkey
 then
-	# statically compiled KLIPS/NETKEY not found; but there seems to be an ipsec module
 	@MODPROBE@ ipsec 2> /dev/null
 fi
 
-if test ! -f $ipsecversion && test ! -f $netkey && @MODPROBE@ -q af_key
+if test ! -f $ipsecversion 
 then
-	# netkey should work then
-	@MODPROBE@ af_key 2> /dev/null
-fi
-if test ! -f $ipsecversion && test ! -f $netkey 
-then
-	echo "ERROR: Failed to load or detect KLIPS and NETKEY"
-	# continuing, because there is another attempt later on with some changed
-	# env settings. Does that actually work?
-	# echo "kernel appears to lack IPsec support (neither CONFIG_KLIPS or CONFIG_NET_KEY are set)"
-	# exit 1
-fi
-# modules shared between klips and netkey
-if test -f $modules
-then
-	# we modprobe hw_random so ipsec verify can complain about not using it
-	@MODPROBE@ -q hw_random 2> /dev/null
-	# padlock must load before aes module
-	@MODPROBE@ -q padlock 2> /dev/null
-	# load the most common ciphers/algo's
-	@MODPROBE@ -q sha256 2> /dev/null
-	@MODPROBE@ -q sha1 2> /dev/null
-	@MODPROBE@ -q md5 2> /dev/null
-	@MODPROBE@ -q des 2> /dev/null
-	@MODPROBE@ -q aes 2> /dev/null
+	echo "No KLIPS support found while requested, desperately falling back to netkey"
+	@MODPROBE@ -q af_key
 
-	if test -f $netkey
+	if test ! -f $netkey
 	then
-		klips=false
-		@MODPROBE@ -q ah4 2> /dev/null
-		@MODPROBE@ -q esp4 2> /dev/null
-		@MODPROBE@ -q ipcomp 2> /dev/null
-		#  xfrm4_tunnel is needed by ipip and ipcomp
-		@MODPROBE@ -q xfrm4_tunnel 2> /dev/null
-		# xfrm_user contains netlink support for IPsec 
-		@MODPROBE@ -q xfrm_user 2> /dev/null
-	fi
-
-	if test ! -f $ipsecversion && $klips
-	then
-		if [ ! -e /proc/ksyms -a ! -e /proc/kallsyms ]
-		then
-			echo "Broken 2.6 kernel without kallsyms, skipping calcgoo (Fedora rpm?)"
-		else
-               		setmodule
-		fi
-               	unset MODPATH MODULECONF        # no user overrides!
-               	depmod -a >/dev/null 2>&1
-               	@MODPROBE@ -v ipsec
-        	if test ! -f $ipsecversion
-        	then
-                	echo "kernel appears to lack IPsec support (neither CONFIG_KLIPS or CONFIG_NET_KEY are set)"
-                	exit 1
-        	fi
+		echo "Even NETKEY support is not there, aborting"
+		exit 1
+	else
+		echo "NETKEY support found. Use protostack=netkey in /etc/ipsec.conf to avoid attempts to use KLIPS. Attempting to continue with NETKEY"
+		exec ipsec _startnetkey
 	fi
 fi
+
+if test ! -f $ipsecversion
+then
+	echo "kernel appears to lack IPsec support (neither CONFIG_KLIPS or CONFIG_NET_KEY were found)"
+	exit 1
+fi
+
 # figure out debugging flags
 case "$debug" in
 '')	debug=none	;;
@@ -378,37 +309,19 @@ then
 	# carry on
 fi
 
-if $klips
+if $mast
+then
+    # flush policy out
+    if iptables -t mangle -L IPSEC >/dev/null
+    then
+	iptables -t mangle -F IPSEC
+    fi
+
+elif $klips
 then
 	# clear tables out in case dregs have been left over
 	ipsec eroute --clear
 	ipsec spi --clear
-elif test $netkey
-then
-	if ip xfrm state > /dev/null 2>&1
-	then
-		ip xfrm state flush
-		ip xfrm policy flush
-	elif type setkey > /dev/null 2>&1
-	then
-	 	# Check that the setkey command is available.
-         	setkeycmd= 	 
-         	PATH=$PATH:/usr/local/sbin 	 
-         	for dir in `echo $PATH | tr ':' ' '` 	 
-         	do 	 
-                	if test -f $dir/setkey -a -x $dir/setkey 	 
-                 	then
-                         	setkeycmd=$dir/setkey
-                         	break                   # NOTE BREAK OUT 
-                	fi
-         	done
-        	$setkeycmd -F
-        	$setkeycmd -FP
-	else
-	
-        	echo "WARNING: cannot flush state/policy database -- \`$1'. Install a newer version of iproute/iproute2 or install the ipsec-tools package to obtain the setkey command." |
-                	logger -s -p daemon.error -t ipsec_setup
-	fi
 fi
 
 # figure out interfaces
diff --git a/openswan/programs/setup/setup.in b/openswan/programs/setup/setup.in
--- a/openswan/programs/setup/setup.in
+++ b/openswan/programs/setup/setup.in
@@ -13,7 +13,6 @@
 # or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 # for more details.
 #
-# RCSID $Id: setup.in,v 1.122.6.7 2007-07-10 03:12:57 paul Exp $
 #
 # ipsec         init.d script for starting and stopping
 #               the IPsec security subsystem (KLIPS and Pluto).
@@ -87,7 +86,13 @@ done
 # Pick up IPsec configuration (until we have done this, successfully, we
 # do not know where errors should go, hence the explicit "daemon.error"s.)
 # Note the "--export", which exports the variables created.
-eval `ipsec _confread $config --optional --varprefix IPSEC --export --type config setup`
+variables=`ipsec addconn $config --varprefix IPSEC --configsetup`
+if [ $? != 0 ]
+then
+    echo "Failed to parse config setup portion of ipsec.conf"
+    exit $?
+fi
+eval $variables
 
 if test " $IPSEC_confreadstatus" != " "
 then
@@ -112,12 +117,12 @@ export IPSECsyslog
 umask 022
 
 mkdir -p /var/run/pluto
-mkdir -p /var/lock/subsys
 
 
 # do it
 case "$1" in
   start|--start|stop|--stop|_autostop|_autostart)
+	# remove for: @cygwin_START@ 
 	# portable way for checking for root
 	if [ ! -w / ]
 	then
@@ -126,6 +131,7 @@ case "$1" in
 			logger -s -p $IPSECsyslog -t ipsec_setup 2>&1
 		exit 1
 	fi
+	# remove for: @cygwin_END@
 	tmp=/var/run/pluto/ipsec_setup.st
 	outtmp=/var/run/pluto/ipsec_setup.out
 	(
