[#2614] if the compiler was not found, output a helpful message
git-svn-id: svn://localhost/svn/uclinux-dist/trunk@5251 3e2a5524-39e8-4cb9-84a9-c49da69cba3a

diff --git a/tools/staging-compiler b/tools/staging-compiler
--- a/tools/staging-compiler
+++ b/tools/staging-compiler
@@ -41,3 +41,6 @@ for p in ${PATH} ; do
 	[ ! -x "${p}/${tool}" ] && continue
 	exec "${p}/${tool}" "$@"
 done
+
+echo "${tool}: command not found; perhaps you need to fix your PATH?" 1>&2
+exit 127
