[#2565] sync with upstream
git-svn-id: svn://localhost/svn/uclinux-dist/trunk@5333 3e2a5524-39e8-4cb9-84a9-c49da69cba3a

diff --git a/user/nessus/nessus-core/nessus-adduser.in b/user/nessus/nessus-core/nessus-adduser.in
--- a/user/nessus/nessus-core/nessus-adduser.in
+++ b/user/nessus/nessus-core/nessus-adduser.in
@@ -86,16 +86,10 @@ fi
 
 # find nessusd by the first path segment, ask for settings
 nessusd_conf=` nessusd -s | sed '/^config_file  *= /!d; s/^[^=]*= *//;'`
-nessusd_users=`nessusd -s | sed       '/^users  *= /!d; s/^[^=]*= *//;'`
 
 # some checks
 [ -s "$nessusd_conf" ] || {
 	echo "Missing or empty configuration file \"$nessusd_conf\"!"
-	exit 2
-}
-[ -n "$nessusd_users" ] || {
-	echo "You must define the user data base entry \"nessusd_users = ...\" in the"
-	echo "configuration file \"$nessusd_conf\"!"
 	exit 2
 }
 
@@ -167,20 +161,32 @@ if [ "$auth" = "cert" ]; then
  echo $Xn "Common Name: $Xc"
  read x && [ -n "$x" ] && dn=$dn/CN=$x
  echo $Xn "e-Mail: $Xc"
- read x && [ -n "$x" ] && dn=$dn/M=$x
+ read x && [ -n "$x" ] && dn=$dn/Email=$x
 else
 askPasswd="Login password :"
+askPasswdAgain="Login password (again) :"
 sayPasswd="Password          :"
 
 ok="n"
 while test "$ok" = "n";
 do
  echo $Xn "$askPasswd $Xc"
+ stty -echo
  read password
- if test -z "$password"; then
+ echo
+ echo $Xn "$askPasswdAgain $Xc"
+ read password_again
+ stty echo
+ echo
+ 
+ if test -z "$password" ; then
    echo "Your password can not be empty."
  else
-   ok="y"
+   if [ "$password" != "$password_again" ]; then
+    echo "Passwords do not match !"
+   else
+    ok="y"
+   fi
 fi
 done
 
@@ -200,41 +206,36 @@ echo "Please see the nessus-adduser(8) man page for the rules syntax"
 echo
 echo "Enter the rules for this user, and hit ctrl-D once you are done : "
 
-# we do not leave any temporary files, hanging around
-# so we trap the exit
-trap "rm -f $TMPDIR/rules.$$;
-      echo; echo INTERRUPT; echo;
-      trap 0;
-      exit 0" 0
 
 echo "(the user can have an empty rules set)"
-cat > $TMPDIR/rules.$$ || {
-  	echo "Error - could not write $TMPDIR/rules.$$"
+mkdir -m 0700 $TMPDIR/nessus-adduser.$$/ || { echo "Error - could not create $TMPDIR/nessus-adduser.$$" ; exit 1; }
+
+cat > $TMPDIR/nessus-adduser.$$/rules.$$ || {
+  	echo "Error - could not write $TMPDIR/nessus-adduser.$$/rules.$$"
 	exit 1
 }
 
 echo 
 echo
 echo "Login             : $login"
-echo "$sayPasswd"         $password
+echo "$sayPasswd ***********" 
 echo "DN                : $dn"
 echo "Rules             : "
 
-cat $TMPDIR/rules.$$
+cat $TMPDIR/nessus-adduser.$$/rules.$$
 
 echo
 echo
 echo $Xn "Is that ok ? (y/n) [y] $Xc"
 
 else
-	cp /dev/null $TMPDIR/rules.$$
+	cp /dev/null $TMPDIR/nessus-adduser.$$/rules.$$
 fi
 read ok
 
 # check for answer, default is Yes, abort on other reply
 case $ok in ''|[Yy]*);; *) 
-    rm -f $TMPDIR/rules.$$
-    trap 0
+    rm -rf $TMPDIR/nessus-adduser.$$
     echo Aborted
     exit 0
 esac
@@ -291,13 +292,11 @@ fi
 
 
 
-cp $TMPDIR/rules.$$ "$localstatedir/nessus/users/$login/auth/rules"
+cp $TMPDIR/nessus-adduser.$$/rules.$$ "$localstatedir/nessus/users/$login/auth/rules"
 
 
-# reset trap, clean up
-trap 0
 
-rm $TMPDIR/rules.$$
+rm -rf $TMPDIR/nessus-adduser.$$
 
 
 
diff --git a/user/nessus/nessus-core/nessus-mkcert.in b/user/nessus/nessus-core/nessus-mkcert.in
--- a/user/nessus/nessus-core/nessus-mkcert.in
+++ b/user/nessus/nessus-core/nessus-mkcert.in
@@ -68,7 +68,7 @@ then
 #
 case `id 2>/dev/null` in 
 uid=0*) 
-    nessusd -g || {
+    $sbindir/nessusd -g || {
 	echo "Executing nessusd failed. Make sure your library loader is configured properly"
 	echo "and that nessusd is in your \$PATH"
 	exit 1
@@ -132,13 +132,12 @@ test -z "$RANDFLAG" -a -z "$RANDFILE" &&
 
 
 
-umask 066
+umask 077
 
 # Set environment
 BASEDIR=${TMPDIR-/tmp}/nessus-mkcert.$$
 mkdir $BASEDIR || exit 1
 
-trap "rm -rf $BASEDIR" 0
 
 CAKEY=$NESSUSPRIV/cakey.pem
 CACERT=$NESSUSPUB/cacert.pem
@@ -153,8 +152,6 @@ SRVCERT=$NESSUSPUB/servercert.pem
 #cln CLNREQ=$BASEDIR/clientreq.pem
 #cln CLNCERT=$BASEDIR/clientcert.pem
 
-##trap "rm -rf $BASEDIR" 0
-trap "echo BASEDIR=$BASEDIR" 0
 
 if [ -z "$QUIET" ];
 then
@@ -335,6 +332,22 @@ EOF
 sed 's/NSCERTTYPE/server/g' < $BASEDIR/std000.cnf > $BASEDIR/std.cnf
 sed 's/NSCERTTYPE/client/g' < $BASEDIR/std000.cnf > $BASEDIR/stdC.cnf
 hostname=`hostname`
+if [ -z "$hostname" ];
+then
+ echo "An error occured while trying to determine hostname !"
+ exit 1
+fi
+# The value for organizationalUnitName must be 64 chars or less;
+#   thus, hostname must be 36 chars or less. If it's too big,
+#   try removing domain.
+
+hostname_len=`echo $hostname| wc -c`
+
+if [ $hostname_len -gt 36 ];
+then
+  hostname=`echo $hostname | cut -d '.' -f 1`
+fi
+
 CAMAIL=ca@$hostname
 #cln CLNMAIL=nessus@$hostname
 SRVMAIL=nessusd@$hostname
@@ -391,7 +404,6 @@ openssl ca -config $BASEDIR/std.cnf -name NessusCA -batch -days $SRVCERT_LIFETIM
 
 ####
 
-trap 0
 
 chmod a+r $CACERT $SRVCERT #cln $CLNCERT
 
diff --git a/user/net-snmp/dist/nsb-nightly b/user/net-snmp/dist/nsb-nightly
--- a/user/net-snmp/dist/nsb-nightly
+++ b/user/net-snmp/dist/nsb-nightly
@@ -1,6 +1,6 @@
 #!/bin/bash
 #
-# $Id$
+# $Id: nsb-nightly,v 1.7 2004/07/03 20:37:14 rstory Exp $
 # Author: Robert Story <rstory@freesnmp.com>
 #
 ########################################################################
@@ -19,6 +19,7 @@ usage()
    echo " -i INSTALLD: install directory [$HOME/build/\$PLATFORM/usr/local]"
    echo ""
    echo " -x : configure extra features for pre-release testing"
+   echo " -C : don't source $HOME/.snmp/nsb-nightly"
    echo ""
    echo " -h : host to upload results to"
    echo " -p : path to upload results to"
@@ -28,31 +29,34 @@ usage()
 #set -x
 
 #
-# find nsb-platform based on te path to this script
+# find nsb-platform based on the path to this script
 #
 EXE_PATH=${0%nsb-nightly}
 EXE_PATH=${EXE_PATH%/}
-if [ -f $EXE_PATH/nsb-functions ];then
-   source $EXE_PATH/nsb-functions
-elif [ -f $HOME/bin/nsb-functions ]; then
-   source $HOME/bin/nsb-functions
-   EXE_PATH=$HOME/bin
-elif [ -f nsb-functions ];then
-   source nsb-functions
-   EXE_APTH=$PWD
+if [ ! -f $EXE_PATH/nsb-functions ];then
+   if [ -f $HOME/bin/nsb-functions ]; then
+      EXE_PATH=$HOME/bin
+   elif [ -f nsb-functions ];then
+      EXE_PATH=$PWD
+   else
+      echo "Cannot find nsb-functions in $EXE_PATH, $HOME/bin or $PWD"
+      exit 1
+   fi
+fi
+
+if [ "x$1" = "x-C" ]; then
+    shift
 else
-   echo "Cannot find nsb-functions in $EXE_PATH, $HOME/bin or $PWD"
-   exit 1
-fi
-
-if [ -f $HOME/.nsb-nightly ];then
-   source $HOME/.nsb-nightly
+    if [ -f $HOME/.snmp/nsb-nightly ];then
+        source $HOME/.snmp/nsb-nightly
+    fi
 fi
 
 ########################################################################
 ########################################################################
 
-# -c -d
+# -r : remove build dir before
+# -R : remove build dir after
 PARMS="$PARMS -r"
 NIGHTLY_VERBOSE=0
 
@@ -62,8 +66,12 @@ do
       b)  NSB_BUILD_DIR=$OPTARG;;
       i)  PARMS="-i $OPTARG $PARMS";;
       s)  NSB_SRC_DIR=$OPTARG;;
-      h)  PARMS="-h $OPTARG $PARMS";;
-      p)  PARMS="-p $OPTARG $PARMS";;
+      h)  NSB_SCP_HOST=$OPTARG
+          PARMS="-h $NSB_SCP_HOST $PARMS"
+          ;;
+      p)  NSB_SCP_DEST=$OPTARG
+          PARMS="-p $NSB_SCP_DEST $PARMS"
+          ;;
       x)  PARMS="-x $PARMS";;
       v)  NIGHTLY_VERBOSE=1;;
       \?)# unknown flag
@@ -77,42 +85,39 @@ if [ $# -ne 1 ]; then
    usage
 fi
 
-VERSION=$1
+NSB_VERSION=$1
+
+source $EXE_PATH/nsb-functions
 
 nsb-default-paths
 
 PARMS="$PARMS -b $NSB_BUILD_DIR -s $NSB_SRC_DIR"
 
-# do this AFTER setting params... so we use same
-# dir that nsb-package will use
-if [ $NSB_SRC_DIR != $NSB_BUILD_DIR ];then
-   NSB_BUILD_DIR=$NSB_BUILD_DIR/$VERSION-`nsb-sysname`
-fi
-
 ########################################################################
 ########################################################################
 echo "Start: `date`"
-echo "Running nsb-package $PARMS $VERSION"
+echo "Running nsb-package $PARMS $NSB_VERSION"
 if [ $NIGHTLY_VERBOSE = 1 ]; then
-    $EXE_PATH/nsb-package $PARMS $VERSION
+    $EXE_PATH/nsb-package $PARMS $NSB_VERSION
 else
-    $EXE_PATH/nsb-package $PARMS $VERSION > /dev/null
+    $EXE_PATH/nsb-package $PARMS $NSB_VERSION > /dev/null
 fi
 RC=$?
-if [ ! -z $NSB_SCP_HOST ]; then
-   nsb-upload $NSB_BUILD_DIR $NSB_SCP_HOST:$NSB_SCP_DEST/$VERSION-`nsb-sysname`
-fi
 echo "Finish: `date`"
 echo -n "Result: "
 case $RC in
     0)  echo "Success!"
-        nsb-prompt "press enter to remove $NSB_BUILD_DIR"
         if [ "x$NSB_BUILD_DIR" = "/" ]; then
             nsb-abort "Not running rm -fR from /"
+        else
+            /bin/rm -fR $NSB_BUILD_DIR > /dev/null 2>&1
         fi
-        /bin/rm -fR $NSB_BUILD_DIR > /dev/null 2>&1
         ;;
-    *) echo "Error!";;
+    *) echo "Error!"
+       if [ ! -z $NSB_SCP_HOST ]; then
+          nsb-upload $NSB_BUILD_DIR $NSB_SCP_HOST:$NSB_SCP_DEST/$NSB_VERSION/$NSB_SUFFIX
+       fi
+        ;;
 esac
 
 exit $RC
